image: node:latest

stages:
  - install
  - build
  - deploy

# services:
#   - docker:dind
cache:
  key: antdpro1
  paths:
    - node_modules

job_install:
  stage: install
  tags:
    - docker
  script:
    - npm install yarn
    - npm install tyarn
    - npx tyarn install

job_build:
  stage: build
  tags:
    - docker
  script:
    - tyarn run build
