image: node:18

stages:
  - install
  - build
  - deploy

# services:
#   - docker:dind

job_install:
  stage: install
  script:
    - npm install yarn
    - npm install tyarn
    - tyarn install

job_build:
  stage: build
  script:
    - tyarn run build
